---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Download Kibana.
  get_url:
    url: https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz
    dest: "{{ workspace }}/kibana-4.0.1.tar.gz"

- name: Expand Kibana.
  command: >
    tar -C {{ workspace }} -xvzf {{ workspace }}/kibana-4.0.1.tar.gz

- name: Ensure www directory exists.
  file:
    path: /var/www
    state: directory

- name: Move Kibana into place.
  command: >
    mv {{ workspace }}/kibana-4.0.1-linux-x64 {{ kibana_root }}
